name: Go package

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Print contents
        run: ls -la testdata/Testrepo

      - name: Init and update submodules
        run: git submodule update --init --recursive

      - name: Build Step
        run: go build -v ./...

      - name: Install Dependencies
        run: go get .

      - name: Run Tests
        run: go test -v ./...

